### ISSUE TITLE
Attribute error while running populate.py

### ISSUE THREAD

**Issue by Pymamid** [samb8s/PsrPopPy#18]
Hello, I am getting an attribute error while running the script populate.py with some specific parameters for rdist ('slab' and 'disk'). 

The command line arguments given are - 
`python2 populate.py -n 2000 -surveys PMSURV -rdist disk -o pmsurvdisk.model`

Error shown - 

```
Traceback (most recent call last):
  File "populate.py", line 586, in <module>
    orbits=args.orbits
  File "populate.py", line 254, in generate
    p.galCoords = go.diskDist()
AttributeError: 'module' object has no attribute 'diskDist'
```

Please let me know if any additional info is required. Thanks!

**Comment by tycohen** [comment]
Please post the code snippet generating the error and the full traceback.

**Comment by Pymamid** [comment]
> Please post the code snippet generating the error and the full traceback.

Thanks. Added them now.

**Comment by Pymamid** [comment]
We figured out the cause of the issue. The problem is fixed if you replace "go.diskDist()" to "go.diskdist()" on line 254 in populate.py.
