### ISSUE TITLE
Escons install - Shared libraries don't load on Mac OSX

### ISSUE THREAD

**Issue by tycohen** [samb8s/PsrPopPy#5]
After installing via escons, when I do `from psrpoppy import populate`, I get the following error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "psrpoppy/populate.py", line 26, in <module>
    import psrpoppy.galacticops as go
  File "psrpoppy/galacticops.py", line 16, in <module>
    ne2001lib = C.CDLL(os.path.join(fortranpath, 'libne2001.so'))
  File "/Users/tcohen/anaconda/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/tcohen/Documents/python/projects/PsrPopPy/psrpoppy/fortran/libne2001.so, 6): image not found
```
Do I still need to run make_mac.csh after this? Doing so installs the *.so libraries in lib/fortran. Copying the *.so files from lib/fortran to psrpoppy/fortran solves the issue.

**Comment by tycohen** [comment]
Resolved #5 Never mind. I don't know why the lib directory stuck around after I pulled the latest commit, it shouldn't have been there. When I reset to the latest commit the issue goes away.
